owner: nairblee777
  repo: monark-upptime

  sites:    
    - name: MonarkOS API
      url: https://api.monarkos.com/health    
    - name: MonarkOS App
      url: https://app.monarkos.com
    - name: Stripe
      url: https://www.stripestatus.com/api/v2/status.json
    - name: Twilio
      url: https://status.twilio.com/api/v2/status.json
    - name: Automations
      url: https://automations.monarkrev.com/healthz

  status-website:
    cname: status.monarkos.com
    name: MonarkOS Status
